name: Deploy release

on:
  pull_request:
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'v')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        run: >-
          stack build
          PATH="`stack path --local-install-root`/test/bin/testReleases-exe"

          gh release create ${{ github.head_ref }}
          "$PATH"
          -F CHANGELOG.md
          --title "${{ github.head_ref }}"
