name: Deploy release

on:
  pull_request:
    types:
      - closed
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    if: github.event.pull_request.merged == true && 
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        run: >-
          gh release create ${{ github.head_ref }}
          "CHANGELOG.md"
          --generate-notes
          --title "${{ github.head_ref }}"
