name: Deploy release

on:
  pull_request:
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'v')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and setup env
        run: |
          stack build
          export RELEASE_PATH="`stack path --local-install-root`/bin/testReleases-exe"


      - name: Release
        run: >-
          gh release create ${{ github.head_ref }}
          "$RELEASE_PATH"
          -F CHANGELOG.md
          --title "${{ github.head_ref }}"
