name: Deploy release

on:
  pull_request:
    types:
      - closed
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        run: >-
          gh release create ${{ github.ref_name }}
          "CHANGELOG.md"
          --generate-notes
          --title "${{ github.head_ref || github.ref_name }}"
